version: '2'

services:
  app1:
    build:
      context: .
    ports:
      - 4000:4000
  
  app2:
    build:
      context: .
    ports:
      - 4001:4000

  app3:
    build:
      context: .
    ports:
      - 4002:4000

  haproxy:
    build:
      context: ./haproxy/
    ports:
      - 8080:80
